apiVersion: core.oam.dev/v1alpha2
kind: ComponentDefinition
metadata:
  name: openstack-vm
  annotations:
    definition.oam.dev/description: Terraform configuration for openstack object
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        "${var.hcl}"
