apiVersion: core.oam.dev/v1alpha2
kind: ComponentDefinition
metadata:
  name: openstack-vm
  annotations:
    definition.oam.dev/description: Terraform configuration for openstack object
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        variable "image" {
               type        = string
             }
             variable "flavor" {
               type        = string
             }
             variable "network_name" {
               type        = string
             }

           resource "openstack_compute_instance_v2" "my_instance" {
             name            = "my_instance"
             image_id      = "${var.image}"
             flavor_id     = "${var.flavor}"
             security_groups = ["default"]
             network {
               name = "${var.network_name}"
             }
           }
           output "instance_id" {
             value = "${openstack_compute_instance_v2.my_instance.id}"
           }
