apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: openstack-kubevela-vm
spec:
  components:
    - name: sample-vm
      type: openstack-vm
      properties:
        image: ca696d11-4b57-4e4a-9971-9dbb618eec03
        flavor: b3492d73-9ade-4138-9cc5-4759a2a92ec9
        network_name: TestNET
        writeConnectionSecretToRef:
          name: instance-outputs
          namespace: default
        providerRef:
          name: openstack