apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: openstack
spec:
  provider: openstack
  region: RegionOne
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: openstack-account-creds
      key: credentials